FROM mcr.microsoft.com/devcontainers/rust:1-1-bookworm

# additional Linux system headers needed for deep system inspection
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends libsystemd-dev pkg-config
  
# create non-root vscode user with matching UID
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=${USER_UID}  

# give 'vscode' (non-root only) user permissions to read system files
RUN usermod -aG sudo vscode